### ISSUE TITLE
大佬，请问在哪里修改端口

### ISSUE THREAD

**Issue by alun1** [mdddj/dd_server_admin#1]
App listening at:                                  ║
        ║  >   Local: http://localhost:8000                  ║
ready - ║  > Network: http://10.0.0.15:8000                  ║
        ║

**Comment by alun1** [comment]
搜索了好久也没看到

**Comment by alun1** [comment]
HOST_NAME 已经改了

**Comment by mdddj** [comment]
改什么端口啊

**Comment by alun1** [comment]
我pnpm dev的时候，║ > Local: http://localhost:8000/ ║
ready - ║ > Network: http://10.0.0.15:8000/ ║监听的是8000，但是搜索不到这个端口在哪里设置的
║

**Comment by mdddj** [comment]
这个是本地调试的端口，怎么改要看 umijs 的文档

**Comment by alun1** [comment]
这个是完整的后端程序，还是后端的页面啊

**Comment by mdddj** [comment]
这个是前端的页面

**Comment by alun1** [comment]
哦～后端不准备开源吗

**Comment by mdddj** [comment]
暂时不开

**Comment by alun1** [comment]
哦

**Comment by alun1** [comment]
好的谢谢
